#pragma once

#include <cstdint>

namespace texas_code { namespace protocol {

	enum class MessageType : std::int32_t {

		UNKNOWN_REQUEST = 0,
		ACTION_REQUEST = 1,
		ACTION_RESPONSE = 2,
		BLIND_MESSAGE = 3,
		CONNECT_REQUEST = 4,
		CONNECT_RESPONSE = 5,
		FLOP_MESSAGE = 6,
		GAME_OVER_MESSAGE = 7,
		HEARTBEAT = 8,
		HOLD_CARDS_MESSAGE = 9,
		INQUIRE_ACTION_MESSAGE = 10,
		INQUIRE_SHOW_DOWN_MESSAGE = 11,
		POT_WIN_MESSAGE = 12,
		RIVER_MESSAGE = 13,
		SEAT_INFO_MESSAGE = 14,
		SHOW_DOWN_MESSAGE = 15,
		SHOW_DOWN_REQUEST = 16,
		SHOW_DOWN_RESPONSE = 17,
		TURN_MESSAGE = 18,
	};
}}
